config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper 
  # do
  #   skip_controllers :authorizations, :applications, :authorized_applications
  # end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :customerinfos, controllers: {registrations: 'customerinfo/registrations'}
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "home#index"
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  get "/carts", to: "carts#index"

  get "/products", to: "products#index"

  get "/transactions", to: "transactions#index"

  get "/about", to: "about#index"

  get "/faq", to: "faq#index"

  get "/selling", to: "selling#index"

  get "/profiles", to: "profiles#index"

  get "/checkout", to: "checkout#index"

  get "/checkout/:id", to: "checkout#index"

  post "/checkout/:id/buy", to: "checkout#buy", as: :buy_checkout

  get "/accounts", to: "accounts#index"

  resources :products do
    member do
      post 'add_to_cart'
      post 'likes', to: 'likes#create'
      delete 'unlike'
      delete :delete_comment
    end
  end
  
  resources :carts, only: [:create, :show, :update, :destroy] do
    delete 'remove_from_cart', on: :member, as: 'remove_from_cart'
    delete 'buy_all', on: :member, as: 'buy_all'
  end

  resources :comments do
    delete :delete_comment, on: :member
    post 'likes', on: :member, to: 'comments#like'
    patch :update_comment, on: :member
    delete 'unlike', on: :member
  end
  
  resources :profiles do
    delete :delete_address, to: 'profiles#destroy', on: :member
  end

  resources :accounts do
    delete :delete_account, to: 'accounts#destroy', on: :member
  end

  resources :home 

  resources :likes, only: [:create, :destroy] 

  # For API calls
  namespace :api do
    namespace :v1 do
      get "/products/product_sold_count", to: "products#product_sold_count"
      get "/products/most_active_customer", to: "products#most_active_customer"
      get "/products/most_liked_product", to: "products#most_liked_product"
      resources :products, only: [:index, :show, :create, :update, :destroy]
      resources :carts, only: [:index, :show, :create, :update, :destroy]
      resources :transactions, only: [:index, :show, :create, :update, :destroy]
      resources :types, only: [:index, :show, :create, :update, :destroy]
      resources :categories, only: [:index, :show, :create, :update, :destroy]
      resources :customs, only: [:show, :index, :create, :update, :destroy] 
    end
  end

  # match '*path', to: 'application#exception_handler', constraints: ->(req) { req.path.exclude?('/rails/active_storage') }, via: [:all]

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :customerinfo
  has_many :likes, as: :likeable
  validates_presence_of :body

  def self.ransackable_attributes(auth_object = nil)
    ["body", "created_at", "customerinfo_id", "id", "id_value", "product_id", "timestamps", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["customerinfo", "likes", "product"]
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_comment, only: [:edit, :update, :like, :unlike, :delete_comment]
    rescue_from Exception, with: :exception_handler

    def new
        @comment = Comment.new
    end
    
    def create
        if current_customerinfo.nil?
            redirect_to new_customerinfo_session_path, notice: "Please login to comment."
            return
        end

        @comment = Comment.new(comment_params)
        
        if @comment.save
            redirect_to product_path(comment_params[:product_id]), notice: 'Comment was successfully created.'
        else
            redirect_to product_path(comment_params[:product_id]), notice: "Comments Cannot be blank"
        end
    end

    def edit
    end

    def update
        if @comment.update(comment_params)
            redirect_to product_path(@comment.product_id), notice: 'Comment was successfully updated.'
        else
            redirect_to product_path(@comment.product_id), notice: 'Error occurred during update.'
        end
    end

    def like
        unless customerinfo_signed_in?
            redirect_to new_customerinfo_session_path, notice: "Please login to like the comment."
            return
        end

        like = Like.new(likeable: @comment, customerinfo_id: current_customerinfo.id)
        if like.save
            redirect_to product_path(@comment.product_id), notice: "You liked this comment."
        else
            redirect_to product_path(@comment.product_id), notice: "Failed to like the comment."
        end
    end

    def unlike
        unless customerinfo_signed_in?
            redirect_to new_customerinfo_session_path, notice: "Please login to unlike the comment."
            return
        end

        Like.find_by(likeable: @comment, customerinfo_id: current_customerinfo.id).destroy
        redirect_to product_path(@comment.product_id), notice: "You unliked this comment."
    end

    def set_comment
        @comment = Comment.find(params[:id])
    end

    def delete_comment
        unless customerinfo_signed_in?
            redirect_to new_customerinfo_session_path, notice: "Please login to delete the comment."
        end

        if @comment.destroy
            redirect_to product_path(@comment.product_id), notice: "Comment was successfully deleted."
        else
            redirect_to product_path(@comment.product_id), notice: "Error deleting comment."
        end
    end

    def exception_handler(exception)
        if exception.is_a?(ActiveRecord::RecordNotFound)
            render file: Rails.public_path.join('404.html'), status: :not_found, layout: false
        else
            render file: Rails.public_path.join('500.html'), status: :internal_server_error, layout: false
        end
    end
    
    private

    def comment_params
        params.require(:comment).permit(:product_id, :customerinfo_id, :body)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<article>
     <div class="comment-box border p-3 mb-3">
        <p><%= comment.body %></p>
        <small class="text-muted d-block text-right">Posted by <%= Customerinfo.find_by(id: comment.customerinfo_id).name %> on <%= comment.created_at.strftime("%B %d, %Y") %></small>
        
        <div class="container">
          <div class="row">
            <div class="col-md-4 order-2 order-md-1">
              <% like_count = Like.where(likeable_type: "Comment", likeable_id: comment.id).count %>
              <% if customerinfo_signed_in? %>
                <% if current_customerinfo.likes? comment %>
                    <%= button_to(unlike_comment_path(comment), method: :delete, class: "btn btn-primary") do %>
                    Unlike <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill btn-primary" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314"/>
                            <text x="50%" y="70%" text-anchor="middle" fill="blue" font-size="8pt"> <%= like_count %></text>
                          </svg>
                    <% end %>
                <% else %>
                    <%= button_to(likes_comment_path(comment), method: :post, class: "btn btn-light") do %>
                     Like <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                            <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15"/>
                            <% if like_count > 0 %>
                              <text x="50%" y="70%" text-anchor="middle" fill="black" font-size="8pt"> <%= like_count %></text>
                            <% end %>
                          </svg>
                    <% end %>
                <% end %>
              <% else %>
                <%= button_to(likes_comment_path(comment), class: "btn btn-light") do %>
                 Like <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                        <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15"/>
                        <% if like_count > 0 %>
                          <text x="50%" y="70%" text-anchor="middle" fill="black" font-size="8pt"> <%= like_count %></text>
                        <% end %>
                      </svg>
                <% end %>
              <% end %>
            </div>
            <% if customerinfo_signed_in? %>
              <% if current_customerinfo.id == comment.customerinfo_id%>
              <div class="col-md-4 order-2 order-md-2">
                <%= button_to "delete", delete_comment_comment_path(comment), method: :delete, class: "btn btn-danger", id: "btn" %>
              </div>
              <div class="col-md-4 order-2 order-md-3">
                <%= button_to "edit", edit_comment_path(comment), method: :get, class: "btn btn-success", id: "btn" %>
              </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
</article>

app/views/comments/_form.html.erb
<style>
  button{
    width: 100%;
  }
</style>
<%= form_for :comment, url: comments_path(:product) do |form| %>

  <div class="form-group">
    <%= form.label :body, "Comment:" %>
    <%= form.text_area :body, class: "form-control", rows: 4 %>

    <% if customerinfo_signed_in?  %>
    <%= form.hidden_field :product_id, value: @product.id %>
    <%= form.hidden_field :customerinfo_id, value: current_customerinfo.id %>
    <% end %>
  </div>

  <%= form.submit "Post Comment", class: "btn btn-warning mt-2" %>
<% end %>

app/views/comments/edit.html.erb
<br>
<div class="container">
    
<h3> Edit Comment </h3>
<br>
<%= form_for @comment, url: "/comments/#{@comment.id}", method: :put do |form| %>

  <div class="form-group">
    <%= form.label :body, "Comment:" %>
    <%= form.text_area :body, class: "form-control", rows: 4 %>

  </div>

  <%= form.submit "Edit Comment", class: "btn btn-warning mt-2" %>
<% end %>


<%= button_to "Back", product_path(@comment.product_id), method: :get, class: "btn btn-warning mt-2"%>
</div>