config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper 
  # do
  #   skip_controllers :authorizations, :applications, :authorized_applications
  # end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :customerinfos, controllers: {registrations: 'customerinfo/registrations'}
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "home#index"
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  get "/carts", to: "carts#index"

  get "/products", to: "products#index"

  get "/transactions", to: "transactions#index"

  get "/about", to: "about#index"

  get "/faq", to: "faq#index"

  get "/selling", to: "selling#index"

  get "/profiles", to: "profiles#index"

  get "/checkout", to: "checkout#index"

  get "/checkout/:id", to: "checkout#index"

  post "/checkout/:id/buy", to: "checkout#buy", as: :buy_checkout

  get "/accounts", to: "accounts#index"

  resources :products do
    member do
      post 'add_to_cart'
      post 'likes', to: 'likes#create'
      delete 'unlike'
      delete :delete_comment
    end
  end
  
  resources :carts, only: [:create, :show, :update, :destroy] do
    delete 'remove_from_cart', on: :member, as: 'remove_from_cart'
    delete 'buy_all', on: :member, as: 'buy_all'
  end

  resources :comments do
    delete :delete_comment, on: :member
    post 'likes', on: :member, to: 'comments#like'
    patch :update_comment, on: :member
    delete 'unlike', on: :member
  end
  
  resources :profiles do
    delete :delete_address, to: 'profiles#destroy', on: :member
  end

  resources :accounts do
    delete :delete_account, to: 'accounts#destroy', on: :member
  end

  resources :home 

  resources :likes, only: [:create, :destroy] 

  # For API calls
  namespace :api do
    namespace :v1 do
      get "/products/product_sold_count", to: "products#product_sold_count"
      get "/products/most_active_customer", to: "products#most_active_customer"
      get "/products/most_liked_product", to: "products#most_liked_product"
      resources :products, only: [:index, :show, :create, :update, :destroy]
      resources :carts, only: [:index, :show, :create, :update, :destroy]
      resources :transactions, only: [:index, :show, :create, :update, :destroy]
      resources :types, only: [:index, :show, :create, :update, :destroy]
      resources :categories, only: [:index, :show, :create, :update, :destroy]
      resources :customs, only: [:show, :index, :create, :update, :destroy] 
    end
  end

  # match '*path', to: 'application#exception_handler', constraints: ->(req) { req.path.exclude?('/rails/active_storage') }, via: [:all]

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    # rescue_from Exception, with: :exception_handler

    def index
        # Fetch frequently sold products details
        @frequently_sold_products_details = Product.joins(:transactions)
        .group(:id)
        .order('count(transactions.product_id) desc')
        .limit(16)

        # Fetch frequently sold products randomly from the fetched details
        @frequently_sold_products_1 = @frequently_sold_products_details.order("RANDOM()").limit(8)

        # Fetch 8 random products if there are fewer than 8 frequently sold products
        if @frequently_sold_products_1.length < 8
            @frequently_sold_products_2 = Product.order("RANDOM()").limit(8)
        else
            @frequently_sold_products_2 = []
        end

        # Fetch gadgets category and related products
        @gadget_categories = Category.find_by(category: "Gadgets")
        if @gadget_categories
            @gadgets = Product.where(category_id: @gadget_categories.id).order("RANDOM()").limit(8)
        else
            @gadgets = []
        end

        # Fetch beauty products category and related products
        @beauty_products_list = Category.find_by(category: "Household")
        if @beauty_products_list
            @beauty_products = Product.where(category_id: @beauty_products_list.id).order("RANDOM()").limit(8)
        else
            @beauty_products = []
        end
    end

    def exception_handler(exception)
        if exception.is_a?(ActiveRecord::RecordNotFound)
            render file: Rails.public_path.join('404.html'), status: :not_found, layout: false
        else
            render file: Rails.public_path.join('500.html'), status: :internal_server_error, layout: false
        end
    end
    
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<footer class="bd-footer py-4 py-md-5 mt-5 bg-body-tertiary">
  <div class="container py-4 py-md-5 px-4 px-md-3 text-body-secondary">
    <div class="row">
      <div class="col-lg-3 mb-3">
        <ul class="list-unstyled small">
          <li class="mb-2">
            lorem ispum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

          </li>
        </ul>
      </div>
      <div class="col-6 col-lg-2 offset-lg-1 mb-3">
        <h5>Links</h5>
        <ul class="list-unstyled">
          <li class="mb-2"><%= link_to "Home", root_path %></li>   
          <li class="mb-2"><%= link_to "About", about_path %></li>
          <li class="mb-2"><%= link_to "FAQ", faq_path %></li>
        </ul>
      </div>
      <div class="col-6 col-lg-2 mb-3">
        <h5>Guides</h5>
        <ul class="list-unstyled">
          <li class="mb-2"><%= link_to "Guides", "https://guides.rubyonrails.org/" %></li>
        </ul>
      </div>
      <div class="col-6 col-lg-2 mb-3">
        <h5>Projects</h5>
        <ul class="list-unstyled">
          <li class="mb-2"><%= link_to "New Project", "http://127.0.0.1:3000/products" %></li>
        </ul>
      </div>
      <div class="col-6 col-lg-2 mb-3">
        <h5>Community</h5>
        <ul class="list-unstyled">
          <li class="mb-2"><%= link_to "Developer support", root_path %></li>
          <li class="mb-2"><%= link_to "Contact support", root_path %></li>
          <li class="mb-2"><%= link_to "Stack Overflow", root_path %></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/home/_header.html.erb
<header class="p-3 text-bg-dark">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <%= link_to(root_path, class: "nav-link px-2 text-secondary") do %>
              Home <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-door-fill" viewBox="0 0 16 16">
                      <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5"/>
                   </svg>
            <% end %>
            
            <%= link_to(carts_path, class: "nav-link px-2 text-secondary") do %>
              Cart <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart3" viewBox="0 0 16 16">
                      <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5M3.102 4l.84 4.479 9.144-.459L13.89 4zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4m7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4m-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2m7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2"/>
                   </svg>
            <% end %>
          
            <%= link_to(products_path, class: "nav-link px-2 text-secondary") do %>
              Sell Product <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cursor-fill" viewBox="0 0 16 16">
                              <path d="M14.082 2.182a.5.5 0 0 1 .103.557L8.528 15.467a.5.5 0 0 1-.917-.007L5.57 10.694.803 8.652a.5.5 0 0 1-.006-.916l12.728-5.657a.5.5 0 0 1 .556.103z"/>
                           </svg>
            <% end %>
          
            <%= link_to(about_path, class: "nav-link px-2 text-secondary") do %>
              About <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-info-circle" viewBox="0 0 16 16">
                      <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/>
                      <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0"/>
                    </svg>
            <% end %>
          
            <%= link_to(faq_path, class: "nav-link px-2 text-secondary") do %>
              FAQ <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-question-circle-fill" viewBox="0 0 16 16">
                    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M5.496 6.033h.825c.138 0 .248-.113.266-.25.09-.656.54-1.134 1.342-1.134.686 0 1.314.343 1.314 1.168 0 .635-.374.927-.965 1.371-.673.489-1.206 1.06-1.168 1.987l.003.217a.25.25 0 0 0 .25.246h.811a.25.25 0 0 0 .25-.25v-.105c0-.718.273-.927 1.01-1.486.609-.463 1.244-.977 1.244-2.056 0-1.511-1.276-2.241-2.673-2.241-1.267 0-2.655.59-2.75 2.286a.237.237 0 0 0 .241.247m2.325 6.443c.61 0 1.029-.394 1.029-.927 0-.552-.42-.94-1.029-.94-.584 0-1.009.388-1.009.94 0 .533.425.927 1.01.927z"/>
                  </svg>
            <% end %>

            <%= link_to(transactions_path, class: "nav-link px-2 text-secondary") do %>
              Transaction History <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-counterclockwise" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M8 3a5 5 0 1 1-4.546 2.914.5.5 0 0 0-.908-.417A6 6 0 1 0 8 2z"/>
                                    <path d="M8 4.466V.534a.25.25 0 0 0-.41-.192L5.23 2.308a.25.25 0 0 0 0 .384l2.36 1.966A.25.25 0 0 0 8 4.466"/>
                                  </svg>
            <% end %>

            <!-- <%= link_to "Sell Products", selling_path, class: "nav-link px-2 text-secondary" %> -->
        </ul>

       
          <input type="search" class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" placeholder="Search Product..." id="myInput" onkeyup="myFunction()" aria-label="Search">
        

        <div class="d-flex justify-content-end">
          <%# <button type="button" class="btn btn-outline-light me-2">Login</button> %>
          <%# <button type="button" class="btn btn-warning">Sign-up</button> %>
          <!-- <%= link_to "Profile", profiles_path, class: "btn btn-outline-light me-2" %> -->
          <% unless customerinfo_signed_in? %>
          <%= link_to "Sign-in", new_customerinfo_session_path, class: "btn btn-outline-light me-2" %>
          <%= link_to "Sign-up", new_customerinfo_registration_path, class: "btn btn-warning" %>
          <% else %>
          <%= link_to "Edit-profile", edit_customerinfo_registration_path, class: "btn btn-outline-light me-2" %>
          <%= button_to "Sign-out", destroy_customerinfo_session_path, method: :delete, class: "btn btn-warning"%>
          <% end %>
        </div>
      </div>
    </div>
  </header>

  <script>
    
    document.getElementById('myInput').addEventListener('keyup', myFunction);

    async function myFunction() {
      if(event.key == "Enter" || event.keyCode == 13) {
        // for showing search results when the enter key is pressed.
        let searchText = document.getElementById('text-1');
        let searchText2 = document.getElementById('text-2');
        let userInput = document.getElementById('myInput').value; 
        let wrapper = document.querySelector('.row');

        if(userInput == "") {
          searchText2.innerHTML = "Please enter a valid search query";
          return;
        }
        searchText.innerHTML = `Search Results for ${userInput}`;

       while (wrapper.firstChild) {
            wrapper.removeChild(wrapper.firstChild);
        }
        
       var div = document.createElement("div");
       div.style.display = "flex";
       div.className = "row";

        // Set the innerHTML of the div to the provided HTML content
        div.innerHTML = `
          <div class="card col-md-3 mb-4 mr-2" aria-hidden="true">
            <img src="https://wallpapercave.com/wp/wp3429906.png" class="card-img-top" alt="..." width="230" height="270">
            <div class="card-body">
              <h5 class="card-title placeholder-glow">
                <span class="placeholder col-6"></span>
              </h5>
              <p class="card-text placeholder-glow">
                <span class="placeholder col-7"></span>
                <span class="placeholder col-4"></span>
              </p>
            </div>
          </div>
          <div class="card col-md-3 mb-4 mr-2" aria-hidden="true">
            <img src="https://wallpapercave.com/wp/wp3429906.png" class="card-img-top" alt="..." width="230" height="270">
            <div class="card-body">
              <h5 class="card-title placeholder-glow">
                <span class="placeholder col-6"></span>
              </h5>
              <p class="card-text placeholder-glow">
                <span class="placeholder col-7"></span>
                <span class="placeholder col-4"></span>
              </p>
            </div>
          </div>
          <div class="card col-md-3 mb-4 mr-2" aria-hidden="true">
            <img src="https://wallpapercave.com/wp/wp3429906.png" class="card-img-top" alt="..." width="230" height="270">
            <div class="card-body">
              <h5 class="card-title placeholder-glow">
                <span class="placeholder col-6"></span>
              </h5>
              <p class="card-text placeholder-glow">
                <span class="placeholder col-7"></span>
                <span class="placeholder col-4"></span>
              </p>
            </div>
          </div>
          <div class="card col-md-3 mb-4 mr-2" aria-hidden="true">
            <img src="https://wallpapercave.com/wp/wp3429906.png" class="card-img-top" alt="..." width="230" height="270">
            <div class="card-body">
              <h5 class="card-title placeholder-glow">
                <span class="placeholder col-6"></span>
              </h5>
              <p class="card-text placeholder-glow">
                <span class="placeholder col-7"></span>
                <span class="placeholder col-4"></span>
              </p>
            </div>
          </div>
        `;

       
        // Append the div to the wrapper
        wrapper.appendChild(div);
        

        console.log(userInput.toUpperCase());
        // for authentication
        let requestBody = {
            "grant_type": "password",
            "email": "hello@example.com",
            "password": "password",
            "client_id": "63h4FRw0Rbs69nI6Gqy2pq8KD7QBUoO9PB1xSCja3oY",
            "client_secret": "IwT4UZ_OzSc_Ijxt-gs23Nlc-ckFpFdCrtJBdVYhBrw"
        }

        let accessToken = await fetch("http://localhost:3000/oauth/token", {
            method: "POST",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify(requestBody)
        }).then(response => response.json()).then(data => {
            console.log(data);
            return data.access_token;
        });

        // for fetching products
        let products = await fetch("http://localhost:3000/api/v1/products", 
          {
            method: "GET",
            headers: {
              "Authorization": `Bearer ${accessToken}`
            }
          }).then(response => response.json()).then(data => {
          console.log(data);
          let result = data.filter(product => (product.name.toUpperCase().includes(userInput.toUpperCase()) || product.description.toUpperCase().includes(userInput.toUpperCase()) || product.brand.toUpperCase().includes(userInput.toUpperCase()) || product.price.toUpperCase().includes(userInput.toUpperCase()) ));
          console.log(result);
          if (result.length == 0) {   
            searchText2.innerHTML = "No products found";
            while (wrapper.firstChild) {
                wrapper.removeChild(wrapper.firstChild);
            }
            return;
          } else {
          searchText2.innerHTML = "Here are the products that match your search";
          }
          
          wrapper.innerHTML = result.map((product, index) => {
            return `<div class="col-md-3 mb-4">
                      <button class="container" onclick="fun(${product.id})">
                          <h5 class="card-title">${product.name}</h5>
                          <img src="${product.image_url}" class="card-img-top" alt="no image available" width="230" height="270">
                          <p class="card-text"><strong> Price: </strong> $ ${product.price}</p>
                      </button>
                    </div>`;
          }).join('');
        });    
        }                             
      }

      function fun(ProductId) {
        console.log("clicked", ProductId);
        window.location.href = `http://localhost:3000/products/${ProductId}`;
      }
  </script>

  <body>

</body>

app/views/home/index.html.erb
<style>
  .product-cards {
   padding-top:40px;
  }
  .scrollable-row {
      overflow-x: auto;
      flex-wrap : nowrap;
      width : 100%;
    }
</style>


<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag(asset_path("carsoul_1.jpg"), alt: "Example Image", class: "d-block w-100 h-20") %>
    </div>
    <div class="carousel-item">
      <%= image_tag(asset_path("carsoul_3.jpg"), alt: "Example Image", class: "d-block w-100 h-20") %>
    </div>
    <div class="carousel-item">
      <%= image_tag(asset_path("carsoul_2.jpg"), alt: "Example Image", class: "d-block w-100 h-20") %>
    </div>
    <div class="carousel-item">
      <%= image_tag(asset_path("carsoul_4.jpg"), alt: "Example Image", class: "d-block w-100 h-20") %>
    </div>
    <div class="carousel-item">
      <%= image_tag(asset_path("carsoul_5.jpg"), alt: "Example Image", class: "d-block w-100 h-20") %>
    </div>
  </div>
</div>
<div class="product-cards">
  <div class="container">

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<% if customerinfo_signed_in? %>
  <h3> <%= "Welcome #{current_customerinfo.name}!"%> </h3>
<% end %>
<br>
<% if notice.present? %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
  <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
  </div>
</div>


<div class="container">
  <div class="search results">
        <h2 id="text-1"></h2>
      
        <h4 id="text-2"></h4>
        
        <div class="row" style="display: flex;">
        </div>
        
    </div>
</div>

<br>

<div class="container">
  <h2> Purchase Products </h2>
  <br>
  <div class="row">
      <% @frequently_sold_products_1&.each do |product| %>
      <div class="col-md-3 mb-4">
        <button class="container">
        <%= link_to  product do %>
        <%= render product%>
        <% end %>
        </button>
        <br>
      </div>
      <% end %>
  </div>


<div class="container">
  <br>
  <h2> Gadgets </h2>
  <br>
  <div class="row">
    <div class="container">
      <div class="row scrollable-row">
        <% @gadgets&.each do |product| %>
        <div class="col mb-4">
          <button class="container">
          <%= link_to  product do %>
          <%= render product%>
          <% end %>
          </button>
          <br>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<br>
<br>

<div class="container">
  <br>
  <h2> Weekend sale </h2>
  <br>
  <div class="row">
        <% @frequently_sold_products_2&.each do |product| %>
        <div class="col-md-3 mb-4">
          <button class="container">
          <%= link_to  product do %>
          <%= render product%>
          <% end %>
          </button>
          <br>
        </div>
        <% end %>
  </div>
</div>

<div class="container">
  <br>
  <h2> Beauty </h2>
  <br>
  <div class="row">
    <div class="container">
      <div class="row scrollable-row">
        <% @beauty_products&.each do |product| %>
        <div class="col mb-4">
          <button class="container">
          <%= link_to  product do %>
          <%= render product%>
          <% end %>
          </button>
          <br>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>


</div>