config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper 
  # do
  #   skip_controllers :authorizations, :applications, :authorized_applications
  # end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :customerinfos, controllers: {registrations: 'customerinfo/registrations'}
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "home#index"
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  get "/carts", to: "carts#index"

  get "/products", to: "products#index"

  get "/transactions", to: "transactions#index"

  get "/about", to: "about#index"

  get "/faq", to: "faq#index"

  get "/selling", to: "selling#index"

  get "/profiles", to: "profiles#index"

  get "/checkout", to: "checkout#index"

  get "/checkout/:id", to: "checkout#index"

  post "/checkout/:id/buy", to: "checkout#buy", as: :buy_checkout

  get "/accounts", to: "accounts#index"

  resources :products do
    member do
      post 'add_to_cart'
      post 'likes', to: 'likes#create'
      delete 'unlike'
      delete :delete_comment
    end
  end
  
  resources :carts, only: [:create, :show, :update, :destroy] do
    delete 'remove_from_cart', on: :member, as: 'remove_from_cart'
    delete 'buy_all', on: :member, as: 'buy_all'
  end

  resources :comments do
    delete :delete_comment, on: :member
    post 'likes', on: :member, to: 'comments#like'
    patch :update_comment, on: :member
    delete 'unlike', on: :member
  end
  
  resources :profiles do
    delete :delete_address, to: 'profiles#destroy', on: :member
  end

  resources :accounts do
    delete :delete_account, to: 'accounts#destroy', on: :member
  end

  resources :home 

  resources :likes, only: [:create, :destroy] 

  # For API calls
  namespace :api do
    namespace :v1 do
      get "/products/product_sold_count", to: "products#product_sold_count"
      get "/products/most_active_customer", to: "products#most_active_customer"
      get "/products/most_liked_product", to: "products#most_liked_product"
      resources :products, only: [:index, :show, :create, :update, :destroy]
      resources :carts, only: [:index, :show, :create, :update, :destroy]
      resources :transactions, only: [:index, :show, :create, :update, :destroy]
      resources :types, only: [:index, :show, :create, :update, :destroy]
      resources :categories, only: [:index, :show, :create, :update, :destroy]
      resources :customs, only: [:show, :index, :create, :update, :destroy] 
    end
  end

  # match '*path', to: 'application#exception_handler', constraints: ->(req) { req.path.exclude?('/rails/active_storage') }, via: [:all]

end

app/models/product.rb
class Product < ApplicationRecord
    has_many :likes, as: :likeable
    has_one_attached :image
    has_many :comments, dependent: :destroy
    belongs_to :category
    belongs_to :type
    has_many :transactions

    validates_presence_of :name, :price, :total_stock_amount, :description
    validates :total_stock_amount, numericality: { only_integer: true, greater_than: 0 }
    validates :price, comparison: { greater_than: 0 }
    validates_associated :category, :type, :comments, :likes, :transactions, on: :create


    def self.frequently_sold_eq(value)
        Product.joins(:transactions).group("products.id").having("count(transactions.id) > ?", value)
    end

    
    def self.ransackable_associations(auth_object = nil)
        ["category", "comments", "image_attachment", "image_blob", "likes", "transactions", "type"]
    end

    def self.ransackable_attributes(auth_object = nil)
        ["brand", "category_id", "created_at", "description", "id", "id_value", "name", "price", "seller_id", "total_stock_amount", "type_id", "updated_at"]
    end

end

app/controllers/api/v1/products_controller.rb
module Api::V1
        class ProductsController < BaseController
            
            # for API calls
            before_action  :set_product, only: [ :update]
            before_action :check_resource_owner, only: [:create, :update, :destroy, :index, :show, :set_product]
            before_action :check_custom_api_resource_owner, only: [:product_sold_count]
            rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

            def index
                products = []
                Product.all.each do |product|
                    product_hash = {
                        id: product.id,
                        name: product.name,
                        description: product.description,
                        brand: product.brand,
                        price: product.price,
                        category_id: product.category_id,
                        type_id: product.type_id,
                        total_stock_amount: product.total_stock_amount,
                        seller_id: product.seller_id,
                        image_url: url_for(product.image)
                      }
                      products << product_hash
                end
                render json: products
            end

            # Custom API controller 
            def product_sold_count
                # @product_with_joins = Product.joins(:transactions).group(:id).order('count(transactions.product_id) desc').count
                @product_with_joins = Transaction.joins(:product)
                @product_with_includes = Transaction.includes(:product)
                @product_with_preload = Transaction.preload(:product)
                @product_with_eager_load = Transaction.eager_load(:product)
                @product_with_strict_loading = Transaction.strict_loading(:product)
                

                product_sold = {}


                # @product_with_joins.each do |key, value|
                #     product_sold[key] = value
                # end

                @product_with_includes.each do |t|
                    # puts t.product.name
                    if product_sold[t.product.name].nil?
                        product_sold[t.product.name] = 1
                    else
                        product_sold[t.product.name] = product_sold[t.product.name] + 1 
                    end
                end

                # product = {
                #     "product_with_joins": @product_with_joins,
                #     "product_with_includes": @product_with_includes,
                #     "product_with_preload": @product_with_preload,
                #     "product_with_eager_load": @product_with_eager_load,
                #     "product_with_strict_loading": @product_with_strict_loading
                # }
                
                # All the queries are giving the same result.

                # render json: product_sold

                # it was not working 
                # @product_with_include_count = Transaction.includes(:product).group(:product_id).order('count(product_id) desc').count

                # product_sold_count_with_include = {}
                # @product_with_include_count.each do |key, value|
                #     puts key.inspect
                # end
                # render json: @product_with_include_count

                @joining_multiple_tables = Transaction.joins(:product, :customerinfo)
                json = {}
                @joining_multiple_tables.each do |t|
                    if json[t.product.name].nil?
                        json[t.product.name] = t.customerinfo.email
                    else
                        json[t.product.name] = json[t.product.name] + ", " + t.customerinfo.email
                    end
                end
                render json: json
            end

            def most_active_customer
                @most_active_customer = Transaction.preload(:customerinfo)
                json = {}
                @most_active_customer.each do |t|
                    if json[t.customerinfo.email].nil?
                        json[t.customerinfo.email] = 1
                    else
                        json[t.customerinfo.email] = json[t.customerinfo.email] + 1
                    end
                end
                render json: json.sort_by {|k,v| v}.reverse.to_h
            end

            def most_liked_product
                # there is a bug in this case, if two products have same name then it won't work.
                # we again loop one array then need to query name in it.
                # suppose if we use an external memory and store the name at end of current loop then the last values are override the previous values.
                @most_liked_product = Like.includes(likeable: :product).where(likeable_type: "Product")
                json = {}
                json_with_product_name = {}
                @most_liked_product.each do |t|
                    if json[t.likeable_id].nil?
                        json[t.likeable_id] = 1
                    else
                        json[t.likeable_id] = json[t.likeable_id] + 1
                    end
                end

                render json: json
            end

            def check_resource_owner
                if doorkeeper_token
                    @current_customerinfo ||= Customerinfo.find_by(id: doorkeeper_token.resource_owner_id)
                    if @current_customerinfo.nil?
                        render json: "Unauthorized access" , status: :unauthorized
                    end
                else
                    render json: "Unauthorized access." , status: :unauthorized
                end
            end

            def check_custom_api_resource_owner
                if doorkeeper_token
                    @current_customerinfo ||= Customerinfo.find_by(id: doorkeeper_token.resource_owner_id)
                    unless @current_customerinfo.nil?
                        render json: "Unauthorized access, You are not allowed to visit this API, Because this API is used for Business purpose." , status: :unauthorized
                    end
                else
                    render json: "Unauthorized access." , status: :unauthorized
                end
            end
                    
            def update
                @product = Product.find(params[:id])
                if @product.update(product_params)
                    render json: @product
                else
                    render json: @product.errors, status: :unprocessable_entity
                end
            end

            def show
                @product = Product.find(params[:id])
                render json: @product
            end

            def destroy
                @product = Product.find(params[:id])
                @product.destroy
                render json: "Product was successfully deleted."
            end

            def create
                @product = Product.new(product_params)
                if @product.save
                    render json: @product
                else
                    render json: @product.errors, status: :unprocessable_entity
                end
            end

            def set_product
                @product = Product.find(params[:id])
            end

            def record_not_found
                render json: { error: "Product not found or Invalid Product ID." }, status: :not_found
            end

            private
            
            def product_params
                params.require(:product).permit(:name, :description, :brand, :price, :category_id, :type_id, :total_stock_amount, :seller_id, :image)
            end  
        end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    
    before_action :set_product, only: [:edit, :update, :show, :destroy]
    rescue_from Exception, with: :exception_handler

    def new
      @product = Product.new
    end

    def index
      @products = Product.all
    end 
    
    def create
      @product = Product.new(product_params)
      if @product.save
        redirect_to product_path(@product), notice: "Product was successfully created." 
      else
        flash[:alert] = @product.errors.full_messages
        render :new, status: :unprocessable_entity 
      end
    end

    def edit
    end

    def update
      if @product.update(product_params)
        redirect_to product_path(@product.id), notice: 'Product was successfully updated.'
      else
        redirect_to product_path(@product.id), notice: 'Error updating product.'
      end
    end

    # for adding product to the cart
    def add_to_cart       
      @cart = Cart.new(customerinfo_id:current_customerinfo.id, product_id: params[:id])
      if @cart.save
        redirect_to carts_path, notice: "Product added to the cart."
      else
        redirect_to carts_path, notice: "Error adding product to the cart."
      end
    end

    def destroy
      if @product.destroy
        redirect_to root_path, notice: "Product was successfully deleted."
      else
        redirect_to product_path(product_params[:id]), notice: "Error deleting product."
      end
    end

    def show
      @comments = @product.comments
    end

    # for handling the all types of exceptions
    def exception_handler(exception)
      if exception.is_a?(ActiveRecord::RecordNotFound)
          render file: Rails.public_path.join('404.html'), status: :not_found, layout: false
      else
          render file: Rails.public_path.join('500.html'), status: :internal_server_error, layout: false
      end
  end
  
    def set_product
      @product = Product.find(params[:id])
    end

    private
  
    def product_params
      params.require(:product).permit(:name, :description, :brand, :price, :category_id, :type_id, :total_stock_amount, :seller_id, :image)
    end
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/products/_form.html.erb
<div class="container">
  <br>
  <%= form_with(model: @product, local: true, html: { multipart: true }, method: :post) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control"%>
  </div>
  <br>
  <div>
    <%= form.label :description %>
    <br>
    <%= form.text_area :description %>
  </div>
  <br>
  <div>
    <%= form.label :brand %>
    <%= form.text_field :brand, class: "form-control" %>
  </div>
  <br>
  <div>
    <%= form.label :price %>
    <%= form.text_field :price, class: "form-control" %>
  </div>
  <br>
  <div>
    <%= form.label :total_stock_amount %>
    <%= form.number_field :total_stock_amount, class: "form-control" %>
  </div>
  <br>
  <div>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  <br>
  <div class="field">
    <%= form.label :category_id %>
    <%= form.collection_select(:category_id, Category.all, :id, :category, prompt: 'Select a Category') %>
  </div>
  <br>
  <div class="field">
    <%= form.label :type_id %>
    <%= form.collection_select(:type_id, Type.all, :id, :typeinfo, prompt: 'Select a Type') %>
  </div>

  <div>
    <%= form.hidden_field :seller_id, value: current_customerinfo.id %>
  </div>
  <br><br>
  <div>
    <%= form.submit 'Create Product' %>
  </div>
<% end %>
</div>

app/views/products/_product.html.erb
<!-- app/views/products/_product.html.erb -->
<!-- <div class="product">
  
  <p><strong>Description:</strong> <%= product.description %></p>
  <p><strong>Brand:</strong> <%= product.brand %></p>
  
  <p><strong>Price:</strong> <%= number_to_currency(product.price) %></p>
  <p><strong>Total Stock Amount:</strong> <%= product.total_stock_amount %></p>

  
</div>
-->
<style>
    .image {
      width: 100%;
      min-height:250px;
      max-height: 300px;
      justify-content: center;
    }
</style>




    <div class="product-card">
        <div class="card-body">
            <h5 class="card-title"><%= product.name %></h5>
            <% if product.image.attached? %>
                <img src="<%= url_for(product.image)%>" width="230" height="270">
            <% else %>
                <p>No image available</p>
            <% end %>
            <p class="card-text"><strong>Price:</strong> <%= number_to_currency(product.price) %></p>
        </div>

    </div>

app/views/products/edit.html.erb
<div class="container">
    <h1> Editing Product </h1>
 

 <%= form_for @product, url: product_path(@product.id), method: :patch do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <br>
  <div>
    <%= form.label :description %>
    <br>
    <%= form.text_area :description %>
  </div>
  <br>
  <div>
    <%= form.label :brand %>
    <%= form.text_field :brand, class: "form-control" %>
  </div>
  <br>
  <div>
    <%= form.label :price %>
    <%= form.text_field :price, class: "form-control" %>
  </div>
  <br>
  <div>
    <%= form.label :total_stock_amount %>
    <%= form.number_field :total_stock_amount, class: "form-control" %>
  </div>
  <br>
  <div class="field">
    <%= form.label :category_id %>
    <%= form.collection_select(:category_id, Category.all, :id, :category, prompt: 'Select a Category') %>
  </div>
  <br>
  <div class="field">
    <%= form.label :type_id %>
    <%= form.collection_select(:type_id, Type.all, :id, :typeinfo, prompt: 'Select a Type') %>
  </div>
  <br>

  <div>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  <br>
  <div>
    <%= form.submit 'Update Product' %>
  </div>
<% end %>
  <br>
<%= link_to 'Back', product_path(@product.id) %>
</div>

app/views/products/index.html.erb
<div class="container">
    <br>
    <h1> Sell Products Online </h2>
    <br>
    <p class="text-justify-center">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores iste excepturi quas impedit unde et voluptatem distinctio repellat nesciunt ipsam, nulla sequi aspernatur? Veritatis odio incidunt quos assumenda nihil pariatur?
        Non exercitationem ad possimus ab consequuntur culpa nisi esse magni. Est, earum, amet qui ipsam maxime debitis unde quibusdam ipsa a iusto inventore voluptate perspiciatis. Magni ab quisquam repellendus excepturi!
    </p>

    <% if customerinfo_signed_in? %>
        <%= button_to "Add new Product", new_product_path, method: :get, class: "btn btn-warning m-4" %> 
    <% end %>
    

    <div class="product-cards">
        <div class="container">

        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

        <% if customerinfo_signed_in? %>
        <h3> <%= "Welcome #{current_customerinfo.name}!"%> </h3>
        <% end %>

        <br>
        <% if notice.present? %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= notice %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <% end %>

        <% if customerinfo_signed_in? %>
            <div class="row">
                <% @products.where(seller_id: current_customerinfo.id).each do |product| %>
                
                <div class="col-md-3 mb-4">
                    <button class="container">
                    <%= link_to  product do %>
                    <%= render product%>
                    <% end %>
                    </button>
                    <br>
                    <br>
                    <br>
                </div>
                
                <% end %>
        <% else %>
            <div class="alert alert-warning" role="alert">
            You need to sign in to see your products
            </div>
        <% end %>
        
        </div>
        </div>
    </div>
</div>

app/views/products/new.html.erb
<div class="container">

    <br>
    <% unless alert.nil? %>
    <strong> <h3 class="text-danger"> Product details can not be blank please fill the form properly </h3> </strong>
        <% alert.each do |e| %>

        <h3 class="text-danger"> <li class="text-danger"> <%= e %> </li></h3> 
        <% end %>
    <% end %>


    <%= render "form", get: @product%>

    <br>

    <%= link_to "back to products", products_path%>
</div>

app/views/products/show.html.erb
<style>
    body {
      min-height: 100vh;
      display: flex;
      flex-direction: column;
    }

    main {
      flex: 3; 
      overflow-y: auto; 
      padding: 20px;
    }

    aside {
      flex: 1; 
      border-left: 1px solid #ddd; 
      padding: 20px;
    }

    .image {
      width: 100%;
      min-height:250px;
      max-height: 500px;
      justify-content: center;
    }

    .like-button.liked {
      background-color: green; 
      color: white;
    }

    #btn{
      width: 100%;
    }

  </style>

<body>


<br>
<h2 class="text-success"> <%= notice %> </h2>
<div class="container-fluid h-100">
  <div class="row h-100">
    <main class="col-md-5">
      
      <div class="card">
        <div class="card-body">
            
            <% if @product.image.attached? %>
                <%= image_tag @product.image, class: "image" %> 
            <% else %>
                <p>No image available</p>
            <% end %>     
        </div>
      </div>
    </main>
    <aside class="col-md-4">
        <div class="h-100">
          
            <h2 class="card-title"><%= @product.name %></h2> 
            <br>
            <% like_count = Like.where(likeable_type: "Product", likeable_id: @product.id).count %>

            <% if customerinfo_signed_in? %>
              <% if current_customerinfo.likes? @product %>
                  <%= button_to(like_path(@product), method: :delete, class: "btn btn-primary") do %>
                   Unlike <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill btn-primary" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314"/>
                            <text x="50%" y="70%" text-anchor="middle" fill="blue" font-size="8pt"> <%= like_count %></text>
                          </svg>

                   <% end %>
              <% else %>
                  <%= button_to(likes_product_path(@product), method: :post, class: "btn btn-light") do %>
                  Like <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                        <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15"/>
                        <% if like_count > 0 %>
                          <text x="50%" y="70%" text-anchor="middle" fill="black" font-size="8pt"> <%= like_count %></text>
                        <% end %>
                      </svg>
                  <% end %>
              <% end %>
            <% else %>
              <%= button_to(likes_product_path(@product), method: :post, class: "btn btn-light") do %>
                  Like <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                        <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15"/>
                        <% if like_count > 0 %>
                          <text x="50%" y="70%" text-anchor="middle" fill="black" font-size="8pt"> <%= like_count %></text>
                        <% end %>
                      </svg>
                <% end %>
            <% end %>
            <br>
            <h5 class="card-text"> <%= @product.description %></h5>
            <br>
            <% category = Category.where(id: @product.category_id) %>
            <% if category.present? %>
              <h5 class="card-text"> <strong> Category: </strong> <%= category.pluck(:category)[0] %> </h5>
            <% end %>
            <% type = Type.where(id: @product.type_id) %>
            <% if type.present? %>
              <h5 class="card-text"> <%= type.pluck(:typeinfo)[0] %> </h5>
            <% end %>
            <h3><strong><%= @product.brand %></strong></h3>
            <br>

            <h3> Comments</h3>
            <%= render 'comments/form', locals: { comment: @comment, product: @product } %>
            
            <% @comments.each do |comment|%>
            <%= render comment %>
            <% end %>
        </div>
    </aside>
    
    <aside class="col-md-3">
      <div class="d-flex flex-column justify-content-flex-start h-100">
        <p class="text-large"><strong ><%= number_to_currency(@product.price) %></strong> </p>
        <p>Free delivery upto <strong>Feb 10</strong>, Make your order soon. If you need fastest delivery then choose our premium plan or else order with fastest delivery will make 5% additional charges.</p>
        <p><strong>total Quantity:</strong><%= @product.total_stock_amount %></p>

        <% if customerinfo_signed_in? %>
            <% unless @product.seller_id.to_i == current_customerinfo.id%>
              <% if (Cart.where(customerinfo_id: current_customerinfo.id).pluck(:product_id)).include?(@product.id) %>
              
                  <%= button_to 'remove from Cart', remove_from_cart_cart_path(@product), method: :delete, class: "btn btn-warning mb-2", id: "btn" %>
              <% else %>
              
                  <%= button_to(add_to_cart_product_path(@product), method: :post, class: "btn btn-warning mb-2" , id: "btn" ) do %>
                      Add to Cart <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart3" viewBox="0 0 16 16">
                                      <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5M3.102 4l.84 4.479 9.144-.459L13.89 4zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4m7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4m-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2m7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2"/>
                                  </svg>
                  <% end %>
              <% end %>
                  <%= button_to 'Buy Now', "/checkout/#{@product.id}", method: :get, class: "btn btn-warning" , id: "btn" %>

            <% else %>
              <%= button_to 'Edit product', edit_product_path(@product), method: :get, class: "btn btn-warning mb-2" , id: "btn" %>
              <%= button_to 'Delete product', product_path(@product), method: :delete, class: "btn btn-danger mb-2" , id: "btn" %>
              
            <% end %>
        <% end %>
      </div>
    </aside>
  </div>
</div>
</body>